server:
  port: ${PORT:8282}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8714/eureka/}


spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}

        - id: reserves
          uri: lb://reserves
          predicates:
            - Path=/reserve-service/**
          filters:
            - RewritePath=/reserve-service/(?<path>.*), /$\{path}

        - id: payments
          uri: lb://payments
          predicates:
            - Path=/payment-service/**
          filters:
            - RewritePath=/payment-service/(?<path>.*), /$\{path}